In [2]:
import pandas as pd
import numpy as np

data ={
    'Weight_in_kg' : [66.5,78.2, 90.1, 120.5, 150.0],
    'Discrete_data' :[1,2,3,4,5],
    'blood_type' : ['A', 'B', 'AB', 'O', 'A'],
    'satisfaction' :['Satisfied', 'Neutral', 'Dissatisfied', 'Satisfied', 'Neutral']
}

df = pd.DataFrame(data)

print("Sample data :")
print(df)
print("\n"+"-"*50 + "\n")


print("Data types of each column :")
print(df.dtypes)
print("\n"+"-"*50 + "\n")
print("Summary statistics for numerical columns :")
print(df.describe())


Sample data :
   Weight_in_kg  Discrete_data blood_type  satisfaction
0          66.5              1          A     Satisfied
1          78.2              2          B       Neutral
2          90.1              3         AB  Dissatisfied
3         120.5              4          O     Satisfied
4         150.0              5          A       Neutral

--------------------------------------------------

Data types of each column :
Weight_in_kg     float64
Discrete_data      int64
blood_type        object
satisfaction      object
dtype: object

--------------------------------------------------

Summary statistics for numerical columns :
       Weight_in_kg  Discrete_data
count      5.000000       5.000000
mean     101.060000       3.000000
std       33.948976       1.581139
min       66.500000       1.000000
25%       78.200000       2.000000
50%       90.100000       3.000000
75%      120.500000       4.000000
max      150.000000       5.000000


In [ ]:
# labelencoding is best to use for ordinal data
import sklearn 
from sklearn.preprocessing import LabelEncoder 
colors = ['Red', 'Green', 'Blue', 'Green', 'Red']
label_encoder = LabelEncoder()
encoded_colors = label_encoder.fit_transform(colors)
print("Original colors:", colors)
print("Encoded colors:", encoded_colors)

Original colors: ['Red', 'Green', 'Blue', 'Green', 'Red']
Encoded colors: [2 1 0 1 2]


In [12]:
for i  , category in enumerate(label_encoder.classes_):
    print(f"{category} -> {i}")
    
    
decoded_colors = label_encoder.inverse_transform(encoded_colors)
print("Decoded colors:", decoded_colors)    

Blue -> 0
Green -> 1
Red -> 2
Decoded colors: ['Red' 'Green' 'Blue' 'Green' 'Red']


In [15]:
from sklearn.preprocessing import OneHotEncoder
vehicles = np.array(['Car', 'Bike', 'Bus', 'Car', 'Bike']).reshape(-1, 1)

print("Original vehicles:"  , vehicles.shape) #(5, 1) which is 5 rows and 1 column
print("Original Data :\n", vehicles.flatten())

one_hot_encoder = OneHotEncoder(sparse_output=False)
one_hot_encoded = one_hot_encoder.fit_transform(vehicles)
print("One-hot encoded vehicles:" , one_hot_encoded.shape) #(5, 3) which is 5 rows and 3 columns
print("One-hot Encoded Data :\n", one_hot_encoded)
categories = one_hot_encoder.categories_[0]
print("Categories:", categories)
for i, category in enumerate(categories):
    print(f"{category} -> {i}")
    


Original vehicles: (5, 1)
Original Data :
 ['Car' 'Bike' 'Bus' 'Car' 'Bike']
One-hot encoded vehicles: (5, 3)
One-hot Encoded Data :
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Categories: ['Bike' 'Bus' 'Car']
Bike -> 0
Bus -> 1
Car -> 2
