In [ ]:
# install numpy
%pip install numpy

In [ ]:

# import numpy
import numpy as np


In [ ]:
# create numpy array
arr1=np.array([4,5,6])
print(arr1)
type(arr1)


numpy.ndarray

In [ ]:
# create python list
l=[4,5,6]
print(l)

[4, 5, 6]


In [ ]:
# create 2D numpy array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# create 2D python list
l=[[1,2,3],[4,5,6]]
print(l)

[[1, 2, 3], [4, 5, 6]]


Array attributes

This section covers the ndim, shape, size, and dtype attributes of an array.

In [ ]:
# numpy array attributes
arr1.ndim


1

In [ ]:
# tells the number of elements in the array
arr1.shape

(3,)

In [ ]:
# tells the data type of the array
arr1.dtype

dtype('int64')

In [ ]:
# tells the total number of elements in the array
arr1.size

3

# How to create a basic array
This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()


In [ ]:

# create 1d array of  ones
a=np.ones(10)
print(a)
# create 2d array of ones
b=np.ones((2,3))
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# create 1d array of  zeros
a=np.zeros(4)
print(a)
# create 2d array of zeros
b=np.zeros((4,5))
print(b)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create empty array
e=np.empty((5))
print(e)
# create 2d empty array
d=np.empty((3,4))
print(d)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# create array with a range of values
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
# create array with a range of values with start and end
a=np.arange(1,10,3)
a

array([1, 4, 7])