In [3]:
print("python")

python


In [ ]:
%pip install numpy

In [3]:
import numpy as np


In [ ]:
arr1=np.array([4,5,6])
print(arr1)
type(arr1)


numpy.ndarray

In [2]:
l=[4,5,6]
print(l)

[4, 5, 6]


In [10]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
l=[[1,2,3],[4,5,6]]
print(l)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
arr1.ndim
arr1.size

1

In [14]:
arr1.shape

(3,)

In [15]:
arr1.dtype

dtype('int64')

In [16]:
arr1.size

3

In [8]:
a=np.ones(10)
print(a)
b=np.ones((2,3))
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
a=np.zeros(4)
print(a)
b=np.zeros((4,5))
print(b)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
e=np.empty((5,2))
print(e)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
a=np.arange(1,10,3)
a

array([1, 4, 7])