In [18]:
# install numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [19]:

# import numpy
import numpy as np


In [20]:
#create a numpy array
arr1=np.array([1, 2, 3, 4, 5])
print("Array 1:", arr1)

Array 1: [1 2 3 4 5]


In [21]:
# create python list
l=[4,5,6]
print(l)

[4, 5, 6]


In [22]:
# create 2D numpy array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [23]:
# create 2D python list
l=[[1,2,3],[4,5,6]]
print(l)

[[1, 2, 3], [4, 5, 6]]


Array attributes

This section covers the ndim, shape, size, and dtype attributes of an array.

In [24]:
# numpy array attributes
arr1.ndim


1

In [25]:
# tells the number of elements in the array
arr1.shape

(5,)

In [26]:
# tells the data type of the array
arr1.dtype

dtype('int64')

In [27]:
# tells the total number of elements in the array
arr1.size

5

# How to create a basic array
This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()


In [28]:

# create 1d array of  ones
a=np.ones(10)
print(a)
# create 2d array of ones
b=np.ones((2,3))
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
# create 1d array of  zeros
a=np.zeros(4)
print(a)
# create 2d array of zeros
b=np.zeros((4,5))
print(b)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
# create empty array
e=np.empty((5))
print(e)
# create 2d empty array
d=np.empty((3,4))
print(d)

[0.00000000e+000 1.12489432e-311 1.12489432e-311 1.12489432e-311
 4.98134024e+151]
[[1.12486066e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.58817677e-052 5.27728954e-091 2.00392079e-076]
 [1.26934480e-076 7.40676768e-038 3.99910963e+252 9.04318901e-067]]


In [31]:
# create array with a range of values
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
# create array with a range of values with start and end
a=np.arange(1,10,3)
a

array([1, 4, 7])

In [33]:
# reshape example
a=np.arange(6)
a.reshape(3,2)
a

array([0, 1, 2, 3, 4, 5])

# linspace and reshape

`np.linspace` creates evenly-spaced numbers over a specified interval.
`reshape` changes array dimensions without modifying data.

In [34]:
# linspace examples
# Create 5 evenly spaced values from 0 to 1
arr1 = np.linspace(0, 1, 5)
print("5 values from 0 to 1:")
print(arr1)

# Create 10 evenly spaced values from 0 to 10
arr2 = np.linspace(0, 10, 10)
print("\n10 values from 0 to 10:")
print(arr2)

# linspace with retstep to get step size
arr3, step = np.linspace(0, 1, 5, retstep=True)
print(f"\n5 values from 0 to 1 with step size {step}:")
print(arr3)

5 values from 0 to 1:
[0.   0.25 0.5  0.75 1.  ]

10 values from 0 to 10:
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]

5 values from 0 to 1 with step size 0.25:
[0.   0.25 0.5  0.75 1.  ]


Adding, removing, and sorting elements

In [35]:

a=np.array([1,3,6,4,7])
a.sort()
a


array([1, 3, 4, 6, 7])

In [36]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
Indexing and slicing
You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [ ]:
data=np.array([1,2,3,4,5])
data[0]  # First element



array([1, 2, 3, 4, 5])

In [ ]:
data[1:4]  # Elements from index 1 to 3


array([2, 3, 4])

In [ ]:
data[-1]  # Last element


np.int64(5)

In [ ]:
data[0:]  # All elements from index 0 onward

In [ ]:
#indexing with conditions
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[a>5]  # Elements greater than 5

array([6, 7, 8, 9])

In [ ]:
a[a%2==0]  # Even elements

array([2, 4, 6, 8])

In [ ]:
a[a>=5]  # Elements greater than or equal to 5

array([5, 6, 7, 8, 9])

In [ ]:
five_up = (a > 5) | (a == 5) # bitwise operator OR
print(five_up)

[[False False False]
 [False  True  True]
 [ True  True  True]]


How to create an array from existing data
This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [39]:
a.view()

array([1, 3, 4, 6, 7])

In [45]:
a1=np.array([[1,2,3],
            [4,5,6]])
b1=np.array([[7,8,9],
            [10,11,12]])

In [48]:
np.vstack((a1,b1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
np.hstack((a1,b1))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [51]:
x = np.arange(1, 25).reshape(2, 12)
x


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [52]:
# If you want to split this array into three equally shaped arrays
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [53]:
# If you want to split your array after the third and fourth column, you’d run:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

np.hsplit(x, (3, 4))

What it does: Instead of splitting into equal parts, we are telling it to split at specific column indices.

(3, 4) means:

First split at column index 3

Then split again at column index 4

Remember: Columns are 0-indexed.

So the splits will be:

Columns 0 to 2 → [: , 0:3]

Column 3 → [:, 3:4]

Columns 4 to 11 → [:, 4:]

In [54]:
x = x[0, :]
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
y=x.copy()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])