In [2]:
# install numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [20]:

# import numpy
import numpy as np


In [4]:
#create a numpy array
arr1=np.array([1, 2, 3, 4, 5])
print("Array 1:", arr1)

Array 1: [1 2 3 4 5]


In [5]:
# create python list
l=[4,5,6]
print(l)

[4, 5, 6]


In [6]:
# create 2D numpy array
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
# create 2D python list
l=[[1,2,3],[4,5,6]]
print(l)

[[1, 2, 3], [4, 5, 6]]


Array attributes

This section covers the ndim, shape, size, and dtype attributes of an array.

In [8]:
# numpy array attributes
arr1.ndim


1

In [9]:
# tells the number of elements in the array
arr1.shape

(5,)

In [10]:
# tells the data type of the array
arr1.dtype

dtype('int64')

In [11]:
# tells the total number of elements in the array
arr1.size

5

# How to create a basic array
This section covers np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace()


In [12]:

# create 1d array of  ones
a=np.ones(10)
print(a)
# create 2d array of ones
b=np.ones((2,3))
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# create 1d array of  zeros
a=np.zeros(4)
print(a)
# create 2d array of zeros
b=np.zeros((4,5))
print(b)

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# create empty array
e=np.empty((5))
print(e)
# create 2d empty array
d=np.empty((3,4))
print(d)

[0.00000000e+000 1.16319402e-311 1.16319402e-311 1.16319402e-311
 0.00000000e+000]
[[1.16320858e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.42413554e-306 1.31370903e-076 6.50455444e-091 4.76187327e-038]
 [2.34085674e-057 3.88577275e-057 3.99910963e+252 9.27500514e-072]]


In [15]:
# create array with a range of values
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [16]:
# create array with a range of values with start and end
a=np.arange(1,10,3)
a

array([1, 4, 7])

In [17]:
# reshape example
a=np.arange(6)
a.reshape(3,2)
a

array([0, 1, 2, 3, 4, 5])

# linspace and reshape

`np.linspace` creates evenly-spaced numbers over a specified interval.
`reshape` changes array dimensions without modifying data.

In [18]:
# linspace examples
# Create 5 evenly spaced values from 0 to 1
arr1 = np.linspace(0, 1, 5)
print("5 values from 0 to 1:")
print(arr1)

# Create 10 evenly spaced values from 0 to 10
arr2 = np.linspace(0, 10, 10)
print("\n10 values from 0 to 10:")
print(arr2)

# linspace with retstep to get step size
arr3, step = np.linspace(0, 1, 5, retstep=True)
print(f"\n5 values from 0 to 1 with step size {step}:")
print(arr3)

5 values from 0 to 1:
[0.   0.25 0.5  0.75 1.  ]

10 values from 0 to 10:
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]

5 values from 0 to 1 with step size 0.25:
[0.   0.25 0.5  0.75 1.  ]


Adding, removing, and sorting elements

In [23]:

a=np.array([1,3,6,4,7])
a.sort()
a


array([1, 3, 4, 6, 7])